Repository 4LG0R1THMS/LifeSync, pull requests merged in 2024-03, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: documentation

#3 Basic Readme
  README.md
Labels: documentation

#4 Created a `docs` folder
  docs/index.md
Labels: documentation

#8 Terraform-Azure deployment configuration
  .terraform/main.tf
  .terraform/outputs.tf
  .terraform/values.tfvars
  .terraform/variables.tf
  LifeSync/LifeSyncMVCWebApp.Common/obj/LifeSyncMVCWebApp.Common.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp.Common/obj/LifeSyncMVCWebApp.Common.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp.Common/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp.Common/obj/project.nuget.cache
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/LifeSyncMVCWebApp.Data.Models.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/LifeSyncMVCWebApp.Data.Models.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/project.nuget.cache
  LifeSync/LifeSyncMVCWebApp.Data/obj/LifeSyncMVCWebApp.Data.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp.Data/obj/LifeSyncMVCWebApp.Data.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp.Data/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp.Data/obj/project.nuget.cache
  LifeSync/LifeSyncMVCWebApp.Services/obj/LifeSyncMVCWebApp.Services.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp.Services/obj/LifeSyncMVCWebApp.Services.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp.Services/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp.Services/obj/project.nuget.cache
  LifeSync/LifeSyncMVCWebApp.Web.ViewModels/obj/LifeSyncMVCWebApp.Web.ViewModels.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp.Web.ViewModels/obj/LifeSyncMVCWebApp.Web.ViewModels.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp.Web.ViewModels/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp.Web.ViewModels/obj/project.nuget.cache
  LifeSync/LifeSyncMVCWebApp/obj/LifeSyncMVCWebApp.Web.csproj.nuget.dgspec.json
  LifeSync/LifeSyncMVCWebApp/obj/LifeSyncMVCWebApp.Web.csproj.nuget.g.props
  LifeSync/LifeSyncMVCWebApp/obj/LifeSyncMVCWebApp.Web.csproj.nuget.g.targets
  LifeSync/LifeSyncMVCWebApp/obj/project.assets.json
  LifeSync/LifeSyncMVCWebApp/obj/project.nuget.cache
  docs/README.md
  docs/deployment/azure_deployment.md
  docs/index.md
Labels: devops

#9 Created a file, which explains the conventions in the project
  CONVENTIONS.md
Labels: documentation

#10 Created a `.NET` workflow configuration
  .github/workflows/dotnet.yml
Labels: devops, security

#11 Fixed the `.NET` workflow
  .github/workflows/dotnet.yml
Labels: devops

#12 FE index page
  front-end/index.html
  front-end/reset.css
  front-end/style.css
  front-end/waves/waves-first.svg
  front-end/waves/waves-second.svg
Labels: front end

#13 README formatting
  README.md
Labels: documentation

#17 Added the Logo to `README.md`
  README.md
  pics/LifeSync.png
Labels: documentation

#18 Added a banner to the README.md
  README.md
  pics/lifesyncbanner.png
Labels: documentation

#19 Some fixed over the deployment docs
  docs/deployment/azure_deployment.md
Labels: documentation

#21 Added custom enums as types
  LifeSync/.vs/LifeSync/FileContentIndex/203d120f-3ade-4b7c-9668-cecfcd24fcac.vsidx
  LifeSync/.vs/LifeSync/FileContentIndex/959e4511-7180-40b7-83e1-d674b6d403fd.vsidx
  LifeSync/.vs/LifeSync/FileContentIndex/9b42a870-afea-4e54-875e-3c520aea9760.vsidx
  LifeSync/.vs/LifeSync/FileContentIndex/9c67cc61-54b8-4854-a2d7-e28246b09325.vsidx
  LifeSync/.vs/LifeSync/v17/.suo
  LifeSync/LifeSyncMVCWebApp.Data.Models/Enums/_PriorityEnum.cs
  LifeSync/LifeSyncMVCWebApp.Data.Models/Enums/_StatusEnum.cs
  LifeSync/LifeSyncMVCWebApp.Data.Models/LifeSyncMVCWebApp.Data.Models.csproj
  LifeSync/LifeSyncMVCWebApp.Data.Models/_Project.cs
  LifeSync/LifeSyncMVCWebApp.Data.Models/_Task.cs
  LifeSync/LifeSyncMVCWebApp.Data.Models/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp.Data.Models/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.pdb
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.csproj.CoreCompileInputs.cache
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.pdb
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/Debug/net6.0/ref/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp.Data.Models/obj/Debug/net6.0/refint/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp.Data/Migrations/20240313214521_addedEnums.Designer.cs
  LifeSync/LifeSyncMVCWebApp.Data/Migrations/20240313214521_addedEnums.cs
  LifeSync/LifeSyncMVCWebApp.Data/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp.Data/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.pdb
  LifeSync/LifeSyncMVCWebApp.Data/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.dll
  LifeSync/LifeSyncMVCWebApp.Data/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.pdb
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.csproj.AssemblyReference.cache
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.csproj.CoreCompileInputs.cache
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.dll
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/LifeSyncMVCWebApp.Data.pdb
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/ref/LifeSyncMVCWebApp.Data.dll
  LifeSync/LifeSyncMVCWebApp.Data/obj/Debug/net6.0/refint/LifeSyncMVCWebApp.Data.dll
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.dll
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.Models.pdb
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.dll
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Data.pdb
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Web.dll
  LifeSync/LifeSyncMVCWebApp/bin/Debug/net6.0/LifeSyncMVCWebApp.Web.pdb
  LifeSync/LifeSyncMVCWebApp/obj/Debug/net6.0/LifeSyncMVCWebApp.Web.csproj.AssemblyReference.cache
  LifeSync/LifeSyncMVCWebApp/obj/Debug/net6.0/LifeSyncMVCWebApp.Web.dll
  LifeSync/LifeSyncMVCWebApp/obj/Debug/net6.0/LifeSyncMVCWebApp.Web.pdb
Labels: back-end

#23 Created a `.gitignore`
  .gitignore
Labels: devops
